# Generated by Django 3.1.5 on 2021-06-08 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedPupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_id', models.IntegerField(null=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading_system.class')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading_system.user')),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_archieved',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='Assigned_pupil',
        ),
    ]
